name: trashbug
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http:
  image_picker: ^0.6.7+17
  dio:
  url_launcher:
  charts_flutter:
  cached_network_image:
  flutter_spinkit: "^4.1.2"
  firebase_auth: ^0.14.0+5
  firebase_dynamic_links: ^0.5.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  provider:
  shared_preferences:
  geolocator:
  font_awesome_flutter:
  path_provider:
  splashscreen:
  flare_flutter:
  firebase_core:
  firebase_analytics:
  cloud_firestore_web:
  firebase_core_web:
  flutter_map:
  geolocation:
  google_maps_flutter:
  json_serializable: ^3.3.0
  # http:
  # mapbox_gl: ^0.9.0bnx

dev_dependencies:
  pedantic: ^1.9.0
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

  # font_awesome_flutter: ^8.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/garbadgeandpeople1.png
    - assets/img/splash.png

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
